import 'dart:math';

class Flag {
  final String flagCodeName;
  final String countryName;

  Flag({required this.flagCodeName, required this.countryName});
}

class CountryGuessingGame {
  List<Flag> countries = [
    Flag(flagCodeName: 'af', countryName: 'Afganistan'),
    Flag(flagCodeName: 'al', countryName: 'Arnavutluk'),
    Flag(flagCodeName: 'dz', countryName: 'Cezayir'),
    Flag(flagCodeName: 'as', countryName: 'Amerikan Samoası'),
    Flag(flagCodeName: 'ad', countryName: 'Andorra'),
    Flag(flagCodeName: 'ao', countryName: 'Angola'),
    Flag(flagCodeName: 'ai', countryName: 'Anguilla'),
    Flag(flagCodeName: 'aq', countryName: 'Antarktika'),
    Flag(flagCodeName: 'ag', countryName: 'Antigua ve Barbuda'),
    Flag(flagCodeName: 'ar', countryName: 'Arjantin'),
    Flag(flagCodeName: 'am', countryName: 'Ermenistan'),
    Flag(flagCodeName: 'aw', countryName: 'Aruba'),
    Flag(flagCodeName: 'au', countryName: 'Avustralya'),
    Flag(flagCodeName: 'at', countryName: 'Avusturya'),
    Flag(flagCodeName: 'az', countryName: 'Azerbaycan'),
    Flag(flagCodeName: 'bs', countryName: 'Bahamalar'),
    Flag(flagCodeName: 'bh', countryName: 'Bahreyn'),
    Flag(flagCodeName: 'bd', countryName: 'Bangladeş'),
    Flag(flagCodeName: 'bb', countryName: 'Barbados'),
    Flag(flagCodeName: 'by', countryName: 'Belarus'),
    Flag(flagCodeName: 'be', countryName: 'Belçika'),
    Flag(flagCodeName: 'bz', countryName: 'Belize'),
    Flag(flagCodeName: 'bj', countryName: 'Benin'),
    Flag(flagCodeName: 'bm', countryName: 'Bermuda'),
    Flag(flagCodeName: 'bt', countryName: 'Bhutan'),
    Flag(flagCodeName: 'bo', countryName: 'Bolivya'),
    Flag(flagCodeName: 'bq', countryName: 'Bonaire, Sint Eustatius ve Saba'),
    Flag(flagCodeName: 'ba', countryName: 'Bosna-Hersek'),
    Flag(flagCodeName: 'bw', countryName: 'Botsvana'),
    Flag(flagCodeName: 'bv', countryName: 'Bouvet Adası'),
    Flag(flagCodeName: 'br', countryName: 'Brezilya'),
    Flag(flagCodeName: 'io', countryName: 'Britanya Hint Okyanusu Toprakları'),
    Flag(flagCodeName: 'bn', countryName: 'Brunei'),
    Flag(flagCodeName: 'bg', countryName: 'Bulgaristan'),
    Flag(flagCodeName: 'bf', countryName: 'Burkina Faso'),
    Flag(flagCodeName: 'bi', countryName: 'Burundi'),
    Flag(flagCodeName: 'cv', countryName: 'Cape Verde'),
    Flag(flagCodeName: 'kh', countryName: 'Kamboçya'),
    Flag(flagCodeName: 'cm', countryName: 'Kamerun'),
    Flag(flagCodeName: 'ca', countryName: 'Kanada'),
    Flag(flagCodeName: 'ky', countryName: 'Cayman Adaları'),
    Flag(flagCodeName: 'cf', countryName: 'Orta Afrika Cumhuriyeti'),
    Flag(flagCodeName: 'td', countryName: 'Çad'),
    Flag(flagCodeName: 'cl', countryName: 'Şili'),
    Flag(flagCodeName: 'cn', countryName: 'Çin'),
    Flag(flagCodeName: 'cx', countryName: 'Christmas Adası'),
    Flag(flagCodeName: 'cc', countryName: 'Cocos (Keeling) Adaları'),
    Flag(flagCodeName: 'co', countryName: 'Kolombiya'),
    Flag(flagCodeName: 'km', countryName: 'Komorlar'),
    Flag(flagCodeName: 'cd', countryName: 'Kongo Demokratik Cumhuriyeti'),
    Flag(flagCodeName: 'cg', countryName: 'Kongo Cumhuriyeti'),
    Flag(flagCodeName: 'ck', countryName: 'Cook Adaları'),
    Flag(flagCodeName: 'cr', countryName: 'Kosta Rika'),
    Flag(flagCodeName: 'hr', countryName: 'Hırvatistan'),
    Flag(flagCodeName: 'cu', countryName: 'Küba'),
    Flag(flagCodeName: 'cw', countryName: 'Curaçao'),
    Flag(flagCodeName: 'cy', countryName: 'Kıbrıs'),
    Flag(flagCodeName: 'cz', countryName: 'Çekya'),
    Flag(flagCodeName: 'ci', countryName: 'Fildişi Sahili'),
    Flag(flagCodeName: 'dk', countryName: 'Danimarka'),
    Flag(flagCodeName: 'dj', countryName: 'Cibuti'),
    Flag(flagCodeName: 'dm', countryName: 'Dominika'),
    Flag(flagCodeName: 'do', countryName: 'Dominik Cumhuriyeti'),
    Flag(flagCodeName: 'ec', countryName: 'Ekvador'),
    Flag(flagCodeName: 'eg', countryName: 'Mısır'),
    Flag(flagCodeName: 'sv', countryName: 'El Salvador'),
    Flag(flagCodeName: 'gq', countryName: 'Ekvator Ginesi'),
    Flag(flagCodeName: 'er', countryName: 'Eritre'),
    Flag(flagCodeName: 'ee', countryName: 'Estonya'),
    Flag(flagCodeName: 'sz', countryName: 'Svaziland'),
    Flag(flagCodeName: 'et', countryName: 'Etiyopya'),
    Flag(flagCodeName: 'fk', countryName: 'Falkland Adaları'),
    Flag(flagCodeName: 'fo', countryName: 'Faroe Adaları'),
    Flag(flagCodeName: 'fj', countryName: 'Fiji'),
    Flag(flagCodeName: 'fi', countryName: 'Finlandiya'),
    Flag(flagCodeName: 'fr', countryName: 'Fransa'),
    Flag(flagCodeName: 'gf', countryName: 'Fransız Guyanası'),
    Flag(flagCodeName: 'pf', countryName: 'Fransız Polinezyası'),
    Flag(flagCodeName: 'tf', countryName: 'Fransız Güney Toprakları'),
    Flag(flagCodeName: 'ga', countryName: 'Gabon'),
    Flag(flagCodeName: 'gm', countryName: 'Gambiya'),
    Flag(flagCodeName: 'ge', countryName: 'Gürcistan'),
    Flag(flagCodeName: 'de', countryName: 'Almanya'),
    Flag(flagCodeName: 'gh', countryName: 'Gana'),
    Flag(flagCodeName: 'gi', countryName: 'Cebelitarık'),
    Flag(flagCodeName: 'gr', countryName: 'Yunanistan'),
    Flag(flagCodeName: 'gl', countryName: 'Grönland'),
    Flag(flagCodeName: 'gd', countryName: 'Granada'),
    Flag(flagCodeName: 'gp', countryName: 'Guadeloupe'),
    Flag(flagCodeName: 'gu', countryName: 'Guam'),
    Flag(flagCodeName: 'gt', countryName: 'Guatemala'),
    Flag(flagCodeName: 'gg', countryName: 'Guernsey'),
    Flag(flagCodeName: 'gn', countryName: 'Gine'),
    Flag(flagCodeName: 'gw', countryName: 'Gine-Bissau'),
    Flag(flagCodeName: 'gy', countryName: 'Guyana'),
    Flag(flagCodeName: 'ht', countryName: 'Haiti'),
    Flag(flagCodeName: 'hm', countryName: 'Heard Adası ve McDonald Adaları'),
    Flag(flagCodeName: 'va', countryName: 'Vatikan'),
    Flag(flagCodeName: 'hn', countryName: 'Honduras'),
    Flag(flagCodeName: 'hk', countryName: 'Hong Kong'),
    Flag(flagCodeName: 'hu', countryName: 'Macaristan'),
    Flag(flagCodeName: 'is', countryName: 'İzlanda'),
    Flag(flagCodeName: 'in', countryName: 'Hindistan'),
    Flag(flagCodeName: 'id', countryName: 'Endonezya'),
    Flag(flagCodeName: 'ir', countryName: 'İran'),
    Flag(flagCodeName: 'iq', countryName: 'Irak'),
    Flag(flagCodeName: 'ie', countryName: 'İrlanda'),
    Flag(flagCodeName: 'im', countryName: 'Man Adası'),
    Flag(flagCodeName: 'il', countryName: 'İsrail'),
    Flag(flagCodeName: 'it', countryName: 'İtalya'),
    Flag(flagCodeName: 'jm', countryName: 'Jamaika'),
    Flag(flagCodeName: 'jp', countryName: 'Japonya'),
    Flag(flagCodeName: 'je', countryName: 'Jersey'),
    Flag(flagCodeName: 'jo', countryName: 'Ürdün'),
    Flag(flagCodeName: 'kz', countryName: 'Kazakistan'),
    Flag(flagCodeName: 'ke', countryName: 'Kenya'),
    Flag(flagCodeName: 'ki', countryName: 'Kiribati'),
    Flag(flagCodeName: 'kp', countryName: 'Kuzey Kore'),
    Flag(flagCodeName: 'kr', countryName: 'Güney Kore'),
    Flag(flagCodeName: 'kw', countryName: 'Kuveyt'),
    Flag(flagCodeName: 'kg', countryName: 'Kırgızistan'),
    Flag(flagCodeName: 'la', countryName: 'Laos'),
    Flag(flagCodeName: 'lv', countryName: 'Letonya'),
    Flag(flagCodeName: 'lb', countryName: 'Lübnan'),
    Flag(flagCodeName: 'ls', countryName: 'Lesotho'),
    Flag(flagCodeName: 'lr', countryName: 'Liberya'),
    Flag(flagCodeName: 'ly', countryName: 'Libya'),
    Flag(flagCodeName: 'li', countryName: 'Lihtenştayn'),
    Flag(flagCodeName: 'lt', countryName: 'Litvanya'),
    Flag(flagCodeName: 'lu', countryName: 'Lüksemburg'),
    Flag(flagCodeName: 'mo', countryName: 'Makao'),
    Flag(flagCodeName: 'mg', countryName: 'Madagaskar'),
    Flag(flagCodeName: 'mw', countryName: 'Malavi'),
    Flag(flagCodeName: 'my', countryName: 'Malezya'),
    Flag(flagCodeName: 'mv', countryName: 'Maldivler'),
    Flag(flagCodeName: 'ml', countryName: 'Mali'),
    Flag(flagCodeName: 'mt', countryName: 'Malta'),
    Flag(flagCodeName: 'mh', countryName: 'Marshall Adaları'),
    Flag(flagCodeName: 'mq', countryName: 'Martinik'),
    Flag(flagCodeName: 'mr', countryName: 'Moritanya'),
    Flag(flagCodeName: 'mu', countryName: 'Mauritius'),
    Flag(flagCodeName: 'yt', countryName: 'Mayotte'),
    Flag(flagCodeName: 'mx', countryName: 'Meksika'),
    Flag(flagCodeName: 'fm', countryName: 'Mikronezya'),
    Flag(flagCodeName: 'md', countryName: 'Moldova'),
    Flag(flagCodeName: 'mc', countryName: 'Monako'),
    Flag(flagCodeName: 'mn', countryName: 'Moğolistan'),
    Flag(flagCodeName: 'me', countryName: 'Karadağ'),
    Flag(flagCodeName: 'ms', countryName: 'Montserrat'),
    Flag(flagCodeName: 'ma', countryName: 'Fas'),
    Flag(flagCodeName: 'mz', countryName: 'Mozambik'),
    Flag(flagCodeName: 'mm', countryName: 'Myanmar'),
    Flag(flagCodeName: 'na', countryName: 'Namibya'),
    Flag(flagCodeName: 'nr', countryName: 'Nauru'),
    Flag(flagCodeName: 'np', countryName: 'Nepal'),
    Flag(flagCodeName: 'nl', countryName: 'Hollanda'),
    Flag(flagCodeName: 'nc', countryName: 'Yeni Kaledonya'),
    Flag(flagCodeName: 'nz', countryName: 'Yeni Zelanda'),
    Flag(flagCodeName: 'ni', countryName: 'Nikaragua'),
    Flag(flagCodeName: 'ne', countryName: 'Nijer'),
    Flag(flagCodeName: 'ng', countryName: 'Nijerya'),
    Flag(flagCodeName: 'nu', countryName: 'Niue'),
    Flag(flagCodeName: 'nf', countryName: 'Norfolk Adası'),
    Flag(flagCodeName: 'mp', countryName: 'Kuzey Mariana Adaları'),
    Flag(flagCodeName: 'no', countryName: 'Norveç'),
    Flag(flagCodeName: 'om', countryName: 'Umman'),
    Flag(flagCodeName: 'pk', countryName: 'Pakistan'),
    Flag(flagCodeName: 'pw', countryName: 'Palau'),
    Flag(flagCodeName: 'ps', countryName: 'Filistin'),
    Flag(flagCodeName: 'pa', countryName: 'Panama'),
    Flag(flagCodeName: 'pg', countryName: 'Papua Yeni Gine'),
    Flag(flagCodeName: 'py', countryName: 'Paraguay'),
    Flag(flagCodeName: 'pe', countryName: 'Peru'),
    Flag(flagCodeName: 'ph', countryName: 'Filipinler'),
    Flag(flagCodeName: 'pn', countryName: 'Pitcairn Adaları'),
    Flag(flagCodeName: 'pl', countryName: 'Polonya'),
    Flag(flagCodeName: 'pt', countryName: 'Portekiz'),
    Flag(flagCodeName: 'pr', countryName: 'Porto Riko'),
    Flag(flagCodeName: 'qa', countryName: 'Katar'),
    Flag(flagCodeName: 're', countryName: 'Reunion'),
    Flag(flagCodeName: 'ro', countryName: 'Romanya'),
    Flag(flagCodeName: 'ru', countryName: 'Rusya'),
    Flag(flagCodeName: 'rw', countryName: 'Ruanda'),
    Flag(flagCodeName: 'bl', countryName: 'Saint Barthelemy'),
    Flag(flagCodeName: 'sh', countryName: 'Saint Helena'),
    Flag(flagCodeName: 'kn', countryName: 'Saint Kitts ve Nevis'),
    Flag(flagCodeName: 'lc', countryName: 'Saint Lucia'),
    Flag(flagCodeName: 'mf', countryName: 'Saint Martin'),
    Flag(flagCodeName: 'pm', countryName: 'Saint Pierre ve Miquelon'),
    Flag(flagCodeName: 'vc', countryName: 'Saint Vincent ve Grenadinler'),
    Flag(flagCodeName: 'ws', countryName: 'Samoa'),
    Flag(flagCodeName: 'sm', countryName: 'San Marino'),
    Flag(flagCodeName: 'st', countryName: 'Sao Tome ve Principe'),
    Flag(flagCodeName: 'sa', countryName: 'Suudi Arabistan'),
    Flag(flagCodeName: 'sn', countryName: 'Senegal'),
    Flag(flagCodeName: 'rs', countryName: 'Sırbistan'),
    Flag(flagCodeName: 'sc', countryName: 'Seyşeller'),
    Flag(flagCodeName: 'sl', countryName: 'Sierra Leone'),
    Flag(flagCodeName: 'sg', countryName: 'Singapur'),
    Flag(flagCodeName: 'sx', countryName: 'Sint Maarten'),
    Flag(flagCodeName: 'sk', countryName: 'Slovakya'),
    Flag(flagCodeName: 'si', countryName: 'Slovenya'),
    Flag(flagCodeName: 'sb', countryName: 'Solomon Adaları'),
    Flag(flagCodeName: 'so', countryName: 'Somali'),
    Flag(flagCodeName: 'za', countryName: 'Güney Afrika'),
    Flag(
        flagCodeName: 'gs',
        countryName: 'Güney Georgia ve Güney Sandwich Adaları'),
    Flag(flagCodeName: 'ss', countryName: 'Güney Sudan'),
    Flag(flagCodeName: 'es', countryName: 'İspanya'),
    Flag(flagCodeName: 'lk', countryName: 'Sri Lanka'),
    Flag(flagCodeName: 'sd', countryName: 'Sudan'),
    Flag(flagCodeName: 'sr', countryName: 'Surinam'),
    Flag(flagCodeName: 'sj', countryName: 'Svalbard ve Jan Mayen'),
    Flag(flagCodeName: 'se', countryName: 'İsveç'),
    Flag(flagCodeName: 'ch', countryName: 'İsviçre'),
    Flag(flagCodeName: 'sy', countryName: 'Suriye'),
    Flag(flagCodeName: 'tw', countryName: 'Tayvan'),
    Flag(flagCodeName: 'tj', countryName: 'Tacikistan'),
    Flag(flagCodeName: 'tz', countryName: 'Tanzanya'),
    Flag(flagCodeName: 'th', countryName: 'Tayland'),
    Flag(flagCodeName: 'tl', countryName: 'Doğu Timor'),
    Flag(flagCodeName: 'tg', countryName: 'Togo'),
    Flag(flagCodeName: 'tk', countryName: 'Tokelau'),
    Flag(flagCodeName: 'to', countryName: 'Tonga'),
    Flag(flagCodeName: 'tt', countryName: 'Trinidad ve Tobago'),
    Flag(flagCodeName: 'tn', countryName: 'Tunus'),
    Flag(flagCodeName: 'tr', countryName: 'Türkiye'),
    Flag(flagCodeName: 'tm', countryName: 'Türkmenistan'),
    Flag(flagCodeName: 'tc', countryName: 'Turks ve Caicos Adaları'),
    Flag(flagCodeName: 'tv', countryName: 'Tuvalu'),
    Flag(flagCodeName: 'ug', countryName: 'Uganda'),
    Flag(flagCodeName: 'ua', countryName: 'Ukrayna'),
    Flag(flagCodeName: 'ae', countryName: 'Birleşik Arap Emirlikleri'),
    Flag(flagCodeName: 'gb', countryName: 'Birleşik Krallık'),
    Flag(flagCodeName: 'us', countryName: 'Amerika Birleşik Devletleri'),
    Flag(
        flagCodeName: 'um',
        countryName: 'Amerika Birleşik Devletleri Küçük Dış Adaları'),
    Flag(flagCodeName: 'uy', countryName: 'Uruguay'),
    Flag(flagCodeName: 'uz', countryName: 'Özbekistan'),
    Flag(flagCodeName: 'vu', countryName: 'Vanuatu'),
    Flag(flagCodeName: 've', countryName: 'Venezuela'),
    Flag(flagCodeName: 'vn', countryName: 'Vietnam'),
    Flag(flagCodeName: 'vg', countryName: 'Virgin Adaları (İngiliz)'),
    Flag(flagCodeName: 'vi', countryName: 'Virgin Adaları (ABD)'),
    Flag(flagCodeName: 'wf', countryName: 'Wallis ve Futuna'),
    Flag(flagCodeName: 'eh', countryName: 'Batı Sahara'),
    Flag(flagCodeName: 'ye', countryName: 'Yemen'),
    Flag(flagCodeName: 'zm', countryName: 'Zambiya'),
    Flag(flagCodeName: 'zw', countryName: 'Zimbabve'),
  ];
  List<Flag> askedCountries = [];
  Flag? _randomCountry;

  Flag QuestionCountry() {
    final random = Random();

    // Sorulmamış ülkeleri bul
    List<Flag> remainingCountries = countries
        .where((country) => !askedCountries.contains(country))
        .toList();

    _randomCountry =
        remainingCountries[random.nextInt(remainingCountries.length)];
    askedCountries.add(_randomCountry!); // Seçilen ülkeyi listeye ekle

    return _randomCountry!;
  }

  List<String> options() {
    if (_randomCountry == null) {
      QuestionCountry();
    }

    final random = Random();
    List<String> optionFlagCodes = [_randomCountry!.flagCodeName];

    while (optionFlagCodes.length < 3) {
      String randomFlagCode =
          countries[random.nextInt(countries.length)].flagCodeName;
      if (!optionFlagCodes.contains(randomFlagCode) &&
          randomFlagCode != _randomCountry!.flagCodeName) {
        optionFlagCodes.add(randomFlagCode);
      }
    }

    optionFlagCodes.shuffle();
    return optionFlagCodes;
  }

  bool checkAnswer(String selectedFlagCode) {
    Flag randomCountry = QuestionCountry();
    return selectedFlagCode == randomCountry.flagCodeName;
  }
}
